> require(downloader)
> dataset_url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
> download(dataset_url, dest = "data.zip", mode = "wb")
> unzip("data.zip", exdir = "./")
> NEI <- readRDS("summarySCC_PM25.rds")
> SCC <- readRDS("Source_Classification_Code.rds")
> library(ggplot2)
> subdata2 <- subset(NEI, fips == "24510")
> baltimore.sources <- aggregate(subdata2[c("Emissions")], list(type = subdata2$type, year = subdata2$year), sum)
> png("Plot3.png")
> qplot(year, Emissions, data = baltimore.sources, color = type, geom= "line")+ ggtitle("Total PM2.5 Emissions in Baltimore County by Source Type") + xlab("Year") + ylab("PM2.5 Emissions")       
> dev.off()
> qplot(year, Emissions, data = baltimore.sources, color = type, geom= "line")+ ggtitle("Total PM2.5 Emissions in Baltimore County by Source Type") + xlab("Year") + ylab("PM2.5 Emissions")   
