> require(downloader)
> dataset_url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
> download(dataset_url, dest = "data.zip", mode = "wb")
> unzip("data.zip", exdir = "./")
> NEI <- readRDS("summarySCC_PM25.rds")
> SCC <- readRDS("Source_Classification_Code.rds")
> data3 <- subset(NEI, fips == "24510" & type=="ON-ROAD")
> baltimore2.sources <- aggregate(data3[c("Emissions")], list(type = data3$type, year = data3$year, zip = data3$fips), sum)
> png("plot5.png")
> qplot(year, Emissions, data = baltimore2.sources, geom= "line") + theme_gray() + ggtitle("Motor Vehicle-Related Emissions in Baltimore County") + xlab("Year") + ylab("Emission Levels")
> dev.off()
> qplot(year, Emissions, data = baltimore2.sources, geom= "line") + theme_gray() + ggtitle("Motor Vehicle-Related Emissions in Baltimore County") + xlab("Year") + ylab("Emission Levels")
