> require(downloader)
> dataset_url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
> download(dataset_url, dest = "data.zip", mode = "wb")
> unzip("data.zip", exdir = "./")
> NEI <- readRDS("summarySCC_PM25.rds")
> SCC <- readRDS("Source_Classification_Code.rds")
> data4 <- subset(NEI, fips == "06037" & type=="ON-ROAD")
> lam.sources <- aggregate(data4[c("Emissions")], list(type = data4$type, year = data4$year, zip = data4$fips), sum)
> c.mv <- rbind(baltimore2.sources, lam.sources)
> png("plot6.png")
> qplot(year, Emissions, data = c.mv, color = zip, geom= "line", ylim = c(-100, 5500)) + ggtitle("Motor Vehicle Emissions in Baltimore (24510) \nvs. Los Angeles (06037) Counties") + xlab("Year") + ylab("Emission Levels")       
> dev.off()
> qplot(year, Emissions, data = c.mv, color = zip, geom= "line", ylim = c(-100, 5500)) + ggtitle("Motor Vehicle Emissions in Baltimore (24510) \nvs. Los Angeles (06037) Counties") + xlab("Year") + ylab("Emission Levels")       
